### ISSUE TITLE
stuck in ground

### ISSUE THREAD

**Issue by izzint** [ss-gnalvesteffer/teardown-freecam#4]
![image](https://user-images.githubusercontent.com/44090193/94496163-99779900-01c1-11eb-9ec7-c08c5a6791c9.png)

**Comment by izzint** [comment]
yes I know im getting 20 fps

**Comment by gnalvesteffer** [comment]
Press Q/E to raise and lower the camera. If you're unable to move, it's because you're not using the first version of the performance test demo.
